const FETCH_REQUEST = 'products/FETCH_REQUEST';
const FETCH_SUCCESS = 'products/FETCH_SUCCESS';
const FETCH_ERROR = 'products/FETCH_ERROR';
const ADD_PRODUCT = 'products/ADD_PRODUCT';
const EDIT_PRODUCT = 'products/EDIT_PRODUCT';
const DELETE_PRODUCT = 'products/DELETE_PRODUCT';

export default {
  FETCH_REQUEST,
  FETCH_SUCCESS,
  FETCH_ERROR,
  ADD_PRODUCT,
  EDIT_PRODUCT,
  DELETE_PRODUCT,
};
